"""tests/test_state_factories.py — Unit tests for state factory functions"""

import pytest

from agents.notebook_state import create_notebook_state
from agents.proposal_gpt_state import create_proposal_gpt_state
from agents.state import create_initial_state
from agents.story_state import create_story_state
from agents.wisdom_state import create_wisdom_state


# ── create_initial_state ──────────────────────────────────────────────────────

class TestCreateInitialState:
    def test_required_fields_present(self):
        state = create_initial_state(goal="test goal", mode="search")
        for key in ("goal", "mode", "session_id", "clarifications", "errors", "completed_steps"):
            assert key in state

    def test_goal_stored(self):
        state = create_initial_state(goal="My Research Goal", mode="search")
        assert state["goal"] == "My Research Goal"

    def test_mode_stored(self):
        for mode in ("document", "search", "hybrid"):
            state = create_initial_state(goal="g", mode=mode)
            assert state["mode"] == mode

    def test_clarifications_default_empty(self):
        state = create_initial_state(goal="g", mode="search")
        assert state["clarifications"] == {}

    def test_clarifications_passed_through(self):
        clarifs = {"audience": "researchers", "depth": "comprehensive"}
        state = create_initial_state(goal="g", mode="search", clarifications=clarifs)
        assert state["clarifications"] == clarifs

    def test_errors_starts_empty(self):
        state = create_initial_state(goal="g", mode="search")
        assert state["errors"] == []

    def test_session_id_autogenerated_if_omitted(self):
        state = create_initial_state(goal="g", mode="search")
        assert isinstance(state["session_id"], str) and state["session_id"]


# ── create_proposal_gpt_state ─────────────────────────────────────────────────

class TestCreateProposalGPTState:
    def test_session_id_present(self):
        state = create_proposal_gpt_state(funding_call_text="Call text here")
        assert "session_id" in state
        assert isinstance(state["session_id"], str) and state["session_id"]

    def test_session_id_passed_through(self):
        state = create_proposal_gpt_state(
            funding_call_text="Call text here", session_id="test-session-1"
        )
        assert state["session_id"] == "test-session-1"

    def test_funding_call_text_stored(self):
        state = create_proposal_gpt_state(funding_call_text="Horizon Europe call for AI proposals")
        assert state["funding_call_text"] == "Horizon Europe call for AI proposals"

    def test_model_name_default(self):
        state = create_proposal_gpt_state(funding_call_text="call text")
        assert state["model_name"] == "llama3.1:8b"

    def test_model_name_passed_through(self):
        state = create_proposal_gpt_state(
            funding_call_text="call text", model_name="llama3.2:3b"
        )
        assert state["model_name"] == "llama3.2:3b"

    def test_num_ctx_default(self):
        state = create_proposal_gpt_state(funding_call_text="call text")
        assert state["num_ctx"] == 32768

    def test_num_ctx_passed_through(self):
        state = create_proposal_gpt_state(funding_call_text="call text", num_ctx=16384)
        assert state["num_ctx"] == 16384

    def test_errors_starts_empty(self):
        state = create_proposal_gpt_state(funding_call_text="call text")
        assert state["errors"] == []

    def test_completed_steps_starts_empty(self):
        state = create_proposal_gpt_state(funding_call_text="call text")
        assert state["completed_steps"] == []


# ── create_story_state ────────────────────────────────────────────────────────

class TestCreateStoryState:
    def test_required_fields_present(self):
        state = create_story_state(
            user_message="Explain attention",
            session_id="s1",
            topic="Transformers",
            model_name="llama3.2:3b",
        )
        for key in ("user_message", "session_id", "topic", "clarifications"):
            assert key in state

    def test_user_message_stored(self):
        state = create_story_state(
            user_message="Hello",
            session_id="s1",
            topic="T",
            model_name="llama3.2:3b",
        )
        assert state["user_message"] == "Hello"

    def test_clarifications_default_empty(self):
        state = create_story_state(
            user_message="Hi",
            session_id="s1",
            topic="T",
            model_name="llama3.2:3b",
        )
        assert state["clarifications"] == {}

    def test_clarifications_passed_through(self):
        c = {"level": "Intermediate"}
        state = create_story_state(
            user_message="Hi",
            session_id="s1",
            topic="T",
            model_name="llama3.2:3b",
            clarifications=c,
        )
        assert state["clarifications"] == c


# ── create_wisdom_state ───────────────────────────────────────────────────────

class TestCreateWisdomState:
    def test_required_fields_present(self):
        state = create_wisdom_state(
            user_message="Help",
            session_id="s1",
            topic="Sleep",
            model_name="llama3.2:3b",
        )
        for key in ("user_message", "session_id", "topic", "clarifications"):
            assert key in state

    def test_clarifications_default_empty(self):
        state = create_wisdom_state(
            user_message="Hi",
            session_id="s1",
            topic="T",
            model_name="llama3.2:3b",
        )
        assert state["clarifications"] == {}

    def test_clarifications_passed_through(self):
        c = {"context": "Personal / health"}
        state = create_wisdom_state(
            user_message="Hi",
            session_id="s1",
            topic="T",
            model_name="llama3.2:3b",
            clarifications=c,
        )
        assert state["clarifications"] == c


# ── create_notebook_state ─────────────────────────────────────────────────────

class TestCreateNotebookState:
    def test_required_fields_present(self):
        state = create_notebook_state(user_message="What is X?", notebook_id="nb1")
        for key in ("user_message", "notebook_id", "model_name", "embed_model",
                    "top_k", "retrieved_chunks", "citations", "completed_steps"):
            assert key in state

    def test_user_message_and_notebook_stored(self):
        state = create_notebook_state(user_message="Hello?", notebook_id="nb42")
        assert state["user_message"] == "Hello?"
        assert state["notebook_id"] == "nb42"

    def test_defaults(self):
        state = create_notebook_state(user_message="q", notebook_id="nb1")
        assert state["retrieved_chunks"] == []
        assert state["citations"] == []
        assert state["suggested_questions"] == []
        assert state["retrieval_mode"] == "empty"
        assert state["completed_steps"] == []
        assert state["progress_pct"] == 0

    def test_top_k_and_embed_model_passed_through(self):
        state = create_notebook_state(
            user_message="q", notebook_id="nb1",
            embed_model="bge-m3", top_k=12,
        )
        assert state["embed_model"] == "bge-m3"
        assert state["top_k"] == 12
