import { act, render, screen, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";
import type { EvidenceRow, PaperLite, SRJobStatus, SRResult, SRTemplate } from "../api/systematicReviewTypes";
import SystematicReviewPage from "./SystematicReviewPage";

const runSystematicReviewMock = vi.fn();
const pollSRJobMock = vi.fn();
const listTemplatesMock = vi.fn();
const checkGrammarMock = vi.fn();

vi.mock("../api/systematicReview", () => ({
  runSystematicReview: (...args: unknown[]) => runSystematicReviewMock(...args),
  pollSRJob: (...args: unknown[]) => pollSRJobMock(...args),
  listTemplates: (...args: unknown[]) => listTemplatesMock(...args),
  checkGrammar: (...args: unknown[]) => checkGrammarMock(...args),
}));

const PAPER: PaperLite = {
  title: "A Survey of Sleep Deprivation",
  authors: ["A. Researcher", "B. Scholar"],
  year: 2023,
  abstract: "Mock abstract about sleep deprivation and memory.",
  url: "https://example.org/mock-paper-1",
  doi: null,
  journal: "Mock Journal of Research",
  source: "arxiv",
  citation_key: "Researcher2023",
  citation_count: 12,
};

const EVIDENCE_ROW: EvidenceRow = {
  title: PAPER.title,
  authors: PAPER.authors,
  year: PAPER.year,
  citation_key: PAPER.citation_key,
  url: PAPER.url,
  doi: PAPER.doi,
  journal: PAPER.journal,
  abstract: PAPER.abstract,
  population: "Mock study population",
  intervention: "Mock intervention",
  comparator: "Mock comparator/control",
  outcome: "Mock primary outcome",
  study_design: "RCT",
  sample_size: "120",
  key_finding: "Mock key finding from this paper.",
  quality: "Medium",
  relevance_score: 4,
};

const TEMPLATE: SRTemplate = {
  key: "sleep-memory",
  label: "Sleep & Memory",
  description: "A guided template for sleep/memory reviews.",
  research_question: "What is the effect of sleep deprivation on working memory?",
  inclusion: ["Peer-reviewed empirical studies", "Human participants"],
  exclusion: ["Animal studies", "Case reports"],
  note: "Adjust the publication window as needed.",
};

function makeResult(overrides: Partial<SRResult> = {}): SRResult {
  return {
    session_id: "sess-1",
    research_question: "Does sleep deprivation affect working memory?",
    inclusion_criteria: ["Peer-reviewed"],
    exclusion_criteria: ["Animal studies"],
    search_queries: ["sleep deprivation memory", "sleep deprivation memory systematic review"],
    model_name: "llama3.1:8b",
    num_ctx: 8192,

    raw_papers: [PAPER],
    screened_papers: [PAPER],
    included_papers: [PAPER],
    excluded_papers: [],

    prisma_flow: { identified: 4, screened: 4, eligibility: 4, included: 4, excluded: 0 },
    evidence_table: [EVIDENCE_ROW],
    narrative_synthesis: "This is a mock narrative synthesis generated by the dev-only mock LLM [1].",
    key_themes: ["Mock theme A", "Mock theme B"],
    research_gaps: ["Mock research gap requiring further study."],
    limitations: "This is a mock limitations paragraph.",
    conclusion: "This is a mock conclusion paragraph.",

    eval_result: {},
    rag_reflection_info: {},

    rob_table: [],
    grade_results: {},
    contradictions: [],

    screener_scores: [],
    preprint_tracking: [],
    citation_graph_html: "",

    trend_data: {},
    evidence_map_data: {},
    concept_drift_data: {},

    errors: [],
    progress_pct: 100,
    ...overrides,
  };
}

/** Returns a controllable pollSRJob double for the NEXT call to pollSRJob(). */
function controllablePoll() {
  let onUpdateRef: ((s: SRJobStatus) => void) | undefined;
  let resolveRef: ((s: SRJobStatus) => void) | undefined;
  let rejectRef: ((e: unknown) => void) | undefined;
  pollSRJobMock.mockImplementationOnce((_jobId: string, onUpdate: (s: SRJobStatus) => void) => {
    onUpdateRef = onUpdate;
    return new Promise<SRJobStatus>((resolve, reject) => {
      resolveRef = resolve;
      rejectRef = reject;
    });
  });
  return {
    update: async (s: SRJobStatus) => {
      await act(async () => {
        onUpdateRef?.(s);
      });
    },
    settle: async (s: SRJobStatus) => {
      await act(async () => {
        resolveRef?.(s);
      });
    },
    fail: async (e: unknown) => {
      await act(async () => {
        rejectRef?.(e);
      });
    },
  };
}

describe("SystematicReviewPage", () => {
  beforeEach(() => {
    runSystematicReviewMock.mockReset();
    pollSRJobMock.mockReset();
    listTemplatesMock.mockReset().mockResolvedValue([]);
    checkGrammarMock.mockReset();
  });

  it("renders the header, intro, and default controls", async () => {
    render(<SystematicReviewPage />);

    expect(
      screen.getByRole("heading", { name: "Mode 1 — Systematic Literature Review" }),
    ).toBeInTheDocument();
    expect(screen.getByLabelText("Research question")).toHaveValue("");
    expect(screen.getByLabelText("Inclusion criteria (one per line)")).toHaveValue("");
    expect(screen.getByLabelText("Exclusion criteria (one per line)")).toHaveValue("");
    expect(screen.getByRole("button", { name: "Run Systematic Review" })).toBeEnabled();

    // TemplatePicker mounts and calls listTemplates() once.
    await screen.findByText("New to systematic reviews? Start from a guided template (optional)");
    expect(listTemplatesMock).toHaveBeenCalledTimes(1);
  });

  it("shows a validation warning for a blank question and does not call the API", async () => {
    const user = userEvent.setup();
    render(<SystematicReviewPage />);

    await user.click(screen.getByRole("button", { name: "Run Systematic Review" }));

    expect(screen.getByText("Please enter a research question.")).toBeInTheDocument();
    expect(runSystematicReviewMock).not.toHaveBeenCalled();
  });

  it("clears a stale validation warning as soon as the user types", async () => {
    const user = userEvent.setup();
    render(<SystematicReviewPage />);

    await user.click(screen.getByRole("button", { name: "Run Systematic Review" }));
    expect(screen.getByText("Please enter a research question.")).toBeInTheDocument();

    await user.type(screen.getByLabelText("Research question"), "a");
    expect(screen.queryByText("Please enter a research question.")).not.toBeInTheDocument();
  });

  it("lets the user apply a guided template, prefilling all three fields", async () => {
    listTemplatesMock.mockResolvedValue([TEMPLATE]);
    const user = userEvent.setup();
    render(<SystematicReviewPage />);

    await user.click(
      await screen.findByText("New to systematic reviews? Start from a guided template (optional)"),
    );
    await user.selectOptions(screen.getByLabelText("Template"), TEMPLATE.key);
    await user.click(screen.getByRole("button", { name: "Use this template" }));

    expect(screen.getByLabelText("Research question")).toHaveValue(TEMPLATE.research_question);
    expect(screen.getByLabelText("Inclusion criteria (one per line)")).toHaveValue(
      TEMPLATE.inclusion.join("\n"),
    );
    expect(screen.getByLabelText("Exclusion criteria (one per line)")).toHaveValue(
      TEMPLATE.exclusion.join("\n"),
    );
  });

  it("runs the happy path: stage labels and step log update live, then renders PRISMA flow and synthesis", async () => {
    const user = userEvent.setup();
    runSystematicReviewMock.mockResolvedValue({ job_id: "job-1" });
    const poll = controllablePoll();

    render(<SystematicReviewPage />);
    await user.type(screen.getByLabelText("Research question"), "Does sleep deprivation affect working memory?");
    await user.type(screen.getByLabelText("Inclusion criteria (one per line)"), "Peer-reviewed");
    await user.type(screen.getByLabelText("Exclusion criteria (one per line)"), "Animal studies");
    await user.click(screen.getByRole("button", { name: "Run Systematic Review" }));

    expect(runSystematicReviewMock).toHaveBeenCalledWith({
      research_question: "Does sleep deprivation affect working memory?",
      inclusion_criteria: ["Peer-reviewed"],
      exclusion_criteria: ["Animal studies"],
    });
    expect(await screen.findByText("Starting…")).toBeInTheDocument();

    await poll.update({
      id: "job-1",
      status: "running",
      stage: "searching",
      stage_info: { progress_pct: 20, label: "Searching", status_detail: "Querying Google Scholar…" },
      error: null,
      result: null,
    });
    expect(await screen.findByText("Searching…")).toBeInTheDocument();
    expect(screen.getByText("20%")).toBeInTheDocument();
    expect(screen.getByText("Querying Google Scholar…")).toBeInTheDocument();

    await poll.update({
      id: "job-1",
      status: "running",
      stage: "screening",
      stage_info: { progress_pct: 50, label: "Screening", status_detail: "Screening 4 papers…" },
      error: null,
      result: null,
    });
    expect(await screen.findByText("Screening…")).toBeInTheDocument();
    expect(screen.getByText("50%")).toBeInTheDocument();

    const result = makeResult();
    await poll.settle({
      id: "job-1",
      status: "done",
      stage: "done",
      stage_info: { progress_pct: 100, label: "Done" },
      error: null,
      result,
    });

    expect(await screen.findByText("Done.")).toBeInTheDocument();
    expect(screen.getByText("100%")).toBeInTheDocument();
    expect(screen.getByText(/Finished in/)).toBeInTheDocument();

    // Step log accumulated both running updates -- collapsed by default.
    const stepLogToggle = screen.getByRole("button", { name: /Step log/ });
    expect(stepLogToggle).toHaveAttribute("aria-expanded", "false");
    await user.click(stepLogToggle);
    expect(screen.getByText(/Searching \(20%\) — Querying Google Scholar…/)).toBeInTheDocument();
    expect(screen.getByText(/Screening \(50%\) — Screening 4 papers…/)).toBeInTheDocument();

    // PRISMA flow + headline counts.
    expect(screen.getByText("Reviewing:", { exact: false })).toBeInTheDocument();
    expect(
      screen.getByText("Queries: 2 · Identified: 1 · Included: 1 · Excluded: 0"),
    ).toBeInTheDocument();

    // Default "Synthesis" tab content.
    expect(screen.getByText("Mock theme A")).toBeInTheDocument();
    expect(
      screen.getByText("This is a mock narrative synthesis generated by the dev-only mock LLM [1]."),
    ).toBeInTheDocument();
    expect(screen.getByText("Mock research gap requiring further study.")).toBeInTheDocument();
    expect(screen.getByText("This is a mock conclusion paragraph.")).toBeInTheDocument();
    expect(screen.getByText("This is a mock limitations paragraph.")).toBeInTheDocument();

    // eval_result has no "overall" key (matches SR's pre-existing behavior) and
    // rag_reflection_info is empty -- neither panel renders.
    expect(screen.queryByText(/Quality Score/)).not.toBeInTheDocument();
    expect(screen.queryByText(/Self-Reflective RAG/)).not.toBeInTheDocument();
  });

  it("switches between result tabs without losing the run", async () => {
    const user = userEvent.setup();
    runSystematicReviewMock.mockResolvedValue({ job_id: "job-2" });
    const poll = controllablePoll();
    render(<SystematicReviewPage />);
    await user.type(screen.getByLabelText("Research question"), "q");
    await user.click(screen.getByRole("button", { name: "Run Systematic Review" }));

    await poll.settle({
      id: "job-2",
      status: "done",
      stage: "done",
      stage_info: {},
      error: null,
      result: makeResult(),
    });
    await screen.findByText("Mock theme A");

    const tablist = screen.getByRole("tablist", { name: "Systematic review results" });
    const evidenceTab = within(tablist).getByRole("tab", { name: "Evidence" });
    await user.click(evidenceTab);

    expect(evidenceTab).toHaveAttribute("aria-selected", "true");
    expect(screen.getByText("Evidence Table (1 included papers)")).toBeInTheDocument();
    expect(screen.queryByText("Mock theme A")).not.toBeInTheDocument();

    const exportTab = within(tablist).getByRole("tab", { name: "Write-up & Export" });
    await user.click(exportTab);
    expect(screen.getByText("Search Queries Used")).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Download as Markdown" })).toBeInTheDocument();
  });

  it("shows a job-error result as a workflow error line", async () => {
    const user = userEvent.setup();
    runSystematicReviewMock.mockResolvedValue({ job_id: "job-3" });
    const poll = controllablePoll();
    render(<SystematicReviewPage />);
    await user.type(screen.getByLabelText("Research question"), "q");
    await user.click(screen.getByRole("button", { name: "Run Systematic Review" }));

    await poll.settle({
      id: "job-3",
      status: "error",
      stage: null,
      stage_info: {},
      error: "search backend exploded",
      result: null,
    });

    expect(await screen.findByText("Workflow error: search backend exploded")).toBeInTheDocument();
  });

  it("shows a workflow error line when runSystematicReview itself rejects", async () => {
    const user = userEvent.setup();
    runSystematicReviewMock.mockRejectedValue(new Error("network down"));
    render(<SystematicReviewPage />);
    await user.type(screen.getByLabelText("Research question"), "q");
    await user.click(screen.getByRole("button", { name: "Run Systematic Review" }));

    expect(await screen.findByText("Workflow error: network down")).toBeInTheDocument();
  });

  it("disables the Run button while a review is in flight", async () => {
    const user = userEvent.setup();
    runSystematicReviewMock.mockResolvedValue({ job_id: "job-4" });
    controllablePoll();
    render(<SystematicReviewPage />);
    await user.type(screen.getByLabelText("Research question"), "q");
    await user.click(screen.getByRole("button", { name: "Run Systematic Review" }));

    expect(await screen.findByRole("button", { name: "Run Systematic Review" })).toBeDisabled();
  });
});
