"""backend/app/mock_llm.py
─────────────────────────
Dev-only stand-in for ``langchain_ollama.ChatOllama``, enabled by setting
``BEESEARCH_MOCK_LLM=1`` before starting the backend. Lets the full
React → FastAPI → agents pipeline be exercised end-to-end (including manual
browser testing) without a reachable Ollama server.

Every ``agents/*.py`` module does ``from langchain_ollama import ChatOllama``
at import time, binding that name into its own module namespace. Patching
``langchain_ollama.ChatOllama`` only takes effect for modules imported
*after* the patch, so ``install_mock_llm()`` must run before any ``agents.*``
module is imported (directly or transitively) — see backend/app/main.py.
"""

from __future__ import annotations

import json
import re
import time
from typing import Any, List

# Small artificial delay so callers polling job status (e.g. the React
# frontend's stage labels, or an E2E test) can observe the "answering" stage
# rather than have it complete instantly between polls -- a real Ollama call
# is never instant either.
_MOCK_INVOKE_DELAY_SECONDS = 0.4


class _MockAIMessage:
    """Minimal stand-in for the AIMessage returned by ChatOllama.invoke()."""

    def __init__(self, content: str) -> None:
        self.content = content


class MockChatOllama:
    """Drop-in replacement for ``langchain_ollama.ChatOllama`` with no network calls.

    Accepts and ignores every constructor kwarg used across the codebase
    (model, base_url, temperature, num_predict, num_ctx, sync_client_kwargs,
    ...) so it can be substituted wherever ``ChatOllama(**kwargs)`` is built,
    and inspects the messages passed to ``invoke()`` to return a plausible,
    content-aware canned response.
    """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        self._kwargs = kwargs

    def invoke(self, messages: List[Any]) -> _MockAIMessage:
        time.sleep(_MOCK_INVOKE_DELAY_SECONDS)
        system = ""
        human = ""
        for m in messages:
            role = getattr(m, "type", "")
            content = getattr(m, "content", "") or ""
            if role == "system":
                system = content
            elif role == "human":
                human = content

        # ── Mode 1 (Systematic Review) branches ─────────────────────────────
        # Checked before the generic Mode 3 branches below: SR's own
        # query_generation and contradiction_detector prompts also contain the
        # substring "JSON array", and would otherwise be misrouted to Mode 3's
        # canned follow-up-questions response below (which returns a JSON array
        # of plain strings -- harmless for query_generation, but a crash for
        # contradiction_detector, whose caller calls .get() on each array item
        # expecting a dict).
        if "PRISMA" in system and "JSON array" in system:
            rq_match = re.search(r"Research question:\s*(.+)", human)
            rq = rq_match.group(1).strip() if rq_match else "the research question"
            return _MockAIMessage(json.dumps([rq, f"{rq} systematic review"]))

        if "screen papers for a systematic review" in system:
            return _MockAIMessage(json.dumps(
                {"decision": "INCLUDE", "reason": "Meets inclusion criteria (mock)."}
            ))

        if "Extract evidence from this paper" in system:
            return _MockAIMessage(json.dumps({
                "population": "Mock study population",
                "intervention": "Mock intervention",
                "comparator": "Mock comparator/control",
                "outcome": "Mock primary outcome",
                "study_design": "RCT",
                "sample_size": "120",
                "key_finding": "Mock key finding from this paper (BEESEARCH_MOCK_LLM=1).",
                "quality": "Medium",
                "relevance_score": 4,
            }))

        if "identifying contradictions in evidence" in system:
            return _MockAIMessage("[]")

        if "narrative synthesis section" in system:
            keys = re.findall(r"^\[([^\]]+)\]", human, re.MULTILINE)
            markers = " ".join(f"[{k}]" for k in keys[:4]) or "[mock]"
            return _MockAIMessage(
                "This is a mock narrative synthesis generated by the dev-only mock LLM "
                "(BEESEARCH_MOCK_LLM=1) because no Ollama server is configured. It stands in "
                f"for a real cross-study narrative synthesis {markers}, discussing convergence "
                "and any conflicting findings across the included papers in formal academic prose."
            )

        if "key_themes" in system and "research_gaps" in system:
            return _MockAIMessage(json.dumps({
                "key_themes": ["Mock theme A", "Mock theme B"],
                "research_gaps": ["Mock research gap requiring further study."],
                "limitations": "This is a mock limitations paragraph (BEESEARCH_MOCK_LLM=1).",
                "conclusion": "This is a mock conclusion paragraph (BEESEARCH_MOCK_LLM=1).",
            }))

        if "JSON array" in system:
            return _MockAIMessage(json.dumps([
                "What do other studies find on this topic?",
                "How does this compare across different populations?",
                "What are the key limitations of this evidence?",
            ]))

        if "NUMBERED SOURCES" in human:
            question_match = re.search(r"QUESTION:\s*(.+)", human)
            question = question_match.group(1).strip() if question_match else "the question"
            cited = re.findall(r"^\[(\d+)\]", human, re.MULTILINE)[:2] or ["1"]
            markers = " ".join(f"[{n}]" for n in cited)
            return _MockAIMessage(
                f'This is a mock grounded answer to "{question}" {markers}, generated by the '
                "dev-only mock LLM (BEESEARCH_MOCK_LLM=1) because no Ollama server is configured. "
                f"It stands in for a real literature-grounded answer {markers} so the full "
                "ask → answer → citations flow can be exercised end-to-end."
            )

        return _MockAIMessage(
            "This is a mock general-knowledge answer generated by the dev-only mock LLM "
            "(BEESEARCH_MOCK_LLM=1) because no published sources were retrieved and no Ollama "
            "server is configured. In a real run this would be an LLM answer with an explicit "
            "not-grounded caveat."
        )


def install_mock_llm() -> None:
    """Monkeypatch ``langchain_ollama.ChatOllama`` with :class:`MockChatOllama`.

    Must be called before any ``agents.*`` module is imported.
    """
    import langchain_ollama

    langchain_ollama.ChatOllama = MockChatOllama
