"""backend/app/mock_llm.py
─────────────────────────
Dev-only stand-in for ``langchain_ollama.ChatOllama``, enabled by setting
``BEESEARCH_MOCK_LLM=1`` before starting the backend. Lets the full
React → FastAPI → agents pipeline be exercised end-to-end (including manual
browser testing) without a reachable Ollama server.

Every ``agents/*.py`` module does ``from langchain_ollama import ChatOllama``
at import time, binding that name into its own module namespace. Patching
``langchain_ollama.ChatOllama`` only takes effect for modules imported
*after* the patch, so ``install_mock_llm()`` must run before any ``agents.*``
module is imported (directly or transitively) — see backend/app/main.py.
"""

from __future__ import annotations

import json
import re
import time
from typing import Any, List

# Small artificial delay so callers polling job status (e.g. the React
# frontend's stage labels, or an E2E test) can observe the "answering" stage
# rather than have it complete instantly between polls -- a real Ollama call
# is never instant either.
_MOCK_INVOKE_DELAY_SECONDS = 0.4


class _MockAIMessage:
    """Minimal stand-in for the AIMessage returned by ChatOllama.invoke()."""

    def __init__(self, content: str) -> None:
        self.content = content


class MockChatOllama:
    """Drop-in replacement for ``langchain_ollama.ChatOllama`` with no network calls.

    Accepts and ignores every constructor kwarg used across the codebase
    (model, base_url, temperature, num_predict, num_ctx, sync_client_kwargs,
    ...) so it can be substituted wherever ``ChatOllama(**kwargs)`` is built,
    and inspects the messages passed to ``invoke()`` to return a plausible,
    content-aware canned response.
    """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        self._kwargs = kwargs

    def invoke(self, messages: List[Any]) -> _MockAIMessage:
        time.sleep(_MOCK_INVOKE_DELAY_SECONDS)
        system = ""
        human = ""
        for m in messages:
            role = getattr(m, "type", "")
            content = getattr(m, "content", "") or ""
            if role == "system":
                system = content
            elif role == "human":
                human = content

        # ── Mode 1 (Systematic Review) branches ─────────────────────────────
        # Checked before the generic Mode 3 branches below: SR's own
        # query_generation and contradiction_detector prompts also contain the
        # substring "JSON array", and would otherwise be misrouted to Mode 3's
        # canned follow-up-questions response below (which returns a JSON array
        # of plain strings -- harmless for query_generation, but a crash for
        # contradiction_detector, whose caller calls .get() on each array item
        # expecting a dict).
        if "PRISMA" in system and "JSON array" in system:
            rq_match = re.search(r"Research question:\s*(.+)", human)
            rq = rq_match.group(1).strip() if rq_match else "the research question"
            return _MockAIMessage(json.dumps([rq, f"{rq} systematic review"]))

        if "screen papers for a systematic review" in system:
            return _MockAIMessage(json.dumps(
                {"decision": "INCLUDE", "reason": "Meets inclusion criteria (mock)."}
            ))

        if "Extract evidence from this paper" in system:
            return _MockAIMessage(json.dumps({
                "population": "Mock study population",
                "intervention": "Mock intervention",
                "comparator": "Mock comparator/control",
                "outcome": "Mock primary outcome",
                "study_design": "RCT",
                "sample_size": "120",
                "key_finding": "Mock key finding from this paper (BEESEARCH_MOCK_LLM=1).",
                "quality": "Medium",
                "relevance_score": 4,
            }))

        if "identifying contradictions in evidence" in system:
            return _MockAIMessage("[]")

        if "narrative synthesis section" in system:
            keys = re.findall(r"^\[([^\]]+)\]", human, re.MULTILINE)
            markers = " ".join(f"[{k}]" for k in keys[:4]) or "[mock]"
            return _MockAIMessage(
                "This is a mock narrative synthesis generated by the dev-only mock LLM "
                "(BEESEARCH_MOCK_LLM=1) because no Ollama server is configured. It stands in "
                f"for a real cross-study narrative synthesis {markers}, discussing convergence "
                "and any conflicting findings across the included papers in formal academic prose."
            )

        if "key_themes" in system and "research_gaps" in system:
            return _MockAIMessage(json.dumps({
                "key_themes": ["Mock theme A", "Mock theme B"],
                "research_gaps": ["Mock research gap requiring further study."],
                "limitations": "This is a mock limitations paragraph (BEESEARCH_MOCK_LLM=1).",
                "conclusion": "This is a mock conclusion paragraph (BEESEARCH_MOCK_LLM=1).",
            }))

        # ── Mode 2 (Research Notebook) analysis pipeline branches ───────────
        # Checked before the generic Mode 3 "JSON array" branch below: the
        # citation-verification prompt also contains the substring "JSON array"
        # and would otherwise be misrouted to Mode 3's canned follow-up-questions
        # response (a JSON array of plain strings) -- harmless for query
        # generation, but a crash here, since citation_verification_node calls
        # .get() on each array item expecting a claim dict.
        if "research fact-checker" in system:
            names = re.findall(r"\[Source \d+: ([^\]\n]+)\]", human)
            primary = names[0] if names else "the source document"
            secondary = names[1] if len(names) > 1 else primary
            return _MockAIMessage(json.dumps([
                {
                    "claim": "The sources report a specific key finding relevant to the summary (mock).",
                    "source_name": primary,
                    "confidence": "HIGH",
                    "supporting_text": "Mock supporting excerpt (BEESEARCH_MOCK_LLM=1).",
                },
                {
                    "claim": "A secondary claim from the summary is paraphrased rather than quoted directly (mock).",
                    "source_name": primary,
                    "confidence": "MEDIUM",
                    "supporting_text": "Mock paraphrased excerpt (BEESEARCH_MOCK_LLM=1).",
                },
                {
                    "claim": "A broader claim in the summary is not clearly traceable to one source (mock).",
                    "source_name": secondary,
                    "confidence": "LOW",
                    "supporting_text": "No direct supporting excerpt found (BEESEARCH_MOCK_LLM=1).",
                },
            ]))

        if "Extract a knowledge graph from the provided research sources" in system:
            return _MockAIMessage(json.dumps({
                "nodes": [
                    {"id": "1", "label": "Mock Research Topic", "type": "concept"},
                    {"id": "2", "label": "Mock Methodology", "type": "method"},
                    {"id": "3", "label": "Mock Dataset", "type": "dataset"},
                    {"id": "4", "label": "Mock Author", "type": "author"},
                    {"id": "5", "label": "Mock Institution", "type": "institution"},
                    {"id": "6", "label": "Mock Related Concept", "type": "concept"},
                ],
                "edges": [
                    {"from": "4", "to": "1", "label": "investigates"},
                    {"from": "1", "to": "2", "label": "uses"},
                    {"from": "2", "to": "3", "label": "applied to"},
                    {"from": "4", "to": "5", "label": "affiliated with"},
                    {"from": "1", "to": "6", "label": "relates to"},
                ],
            }))

        if "paragraphs covering" in system:
            doc_match = re.search(r"Document:\s*(.+)", human)
            name = doc_match.group(1).strip() if doc_match else "the document"
            return _MockAIMessage(
                f"This is a mock single-document summary of '{name}' generated by the dev-only "
                "mock LLM (BEESEARCH_MOCK_LLM=1) because no Ollama server is configured. It stands "
                "in for a real 3-4 paragraph summary covering the document's main argument, "
                "methodology, key findings, and implications."
            )

        if "sentences covering its main argument" in system:
            doc_match = re.search(r"Document:\s*(.+)", human)
            name = doc_match.group(1).strip() if doc_match else "the document"
            return _MockAIMessage(
                f"Mock per-document summary of '{name}' (BEESEARCH_MOCK_LLM=1): stands in for a "
                "real 3-4 sentence summary of this document's main argument, methods, and key finding."
            )

        if "research analyst synthesising multiple sources" in system:
            names = re.findall(r"\[Source \d+: ([^\]\n]+)\]", human)
            cited = ", ".join(names[:3]) if names else "the provided sources"
            return _MockAIMessage(
                "**Overview** — This is a mock cross-document synthesis generated by the dev-only "
                f"mock LLM (BEESEARCH_MOCK_LLM=1) covering {cited}.\n\n"
                "**Common Themes** — Mock shared themes identified across the sources.\n\n"
                "**Complementary Contributions** — Mock description of how the sources build on "
                "each other.\n\n"
                "**Contradictions / Tensions** — No contradictions identified (mock).\n\n"
                "**Key Takeaways** — This stands in for a real structured synthesis of the "
                "notebook's sources."
            )

        if "comprehensive study guide from research material" in system:
            return _MockAIMessage(
                "## Key Concepts\n"
                "- **Mock Concept A** — a mock one-sentence definition (BEESEARCH_MOCK_LLM=1).\n"
                "- **Mock Concept B** — a mock one-sentence definition (BEESEARCH_MOCK_LLM=1).\n\n"
                "## Glossary\n"
                "| Term | Definition | Source |\n"
                "|------|------------|--------|\n"
                "| Mock Term | A mock definition | Mock Source |\n\n"
                "## Review Questions\n"
                "**Q:** What is this mock study guide standing in for?\n"
                "**A:** A real LLM-generated study guide (BEESEARCH_MOCK_LLM=1).\n\n"
                "## Quick Summary\n"
                "This is a mock quick summary generated by the dev-only mock LLM because no "
                "Ollama server is configured."
            )

        if "podcast script writer" in system:
            return _MockAIMessage(
                "HOST: Welcome back to the show! Today we're digging into some fascinating "
                "research (mock podcast intro, BEESEARCH_MOCK_LLM=1).\n"
                "EXPERT: Thanks for having me. This stands in for a real two-speaker podcast "
                "script because no Ollama server is configured.\n"
                "HOST: Before we wrap up, what should our listeners take away from this?\n"
                "EXPERT: The main takeaway is that this is mock dialogue generated for "
                "end-to-end testing.\n"
                "HOST: Great insights — thanks so much for joining us, and thanks to everyone "
                "listening!"
            )

        # ── Mode 2 (Research Notebook) standalone advanced-tools branches (Phase C) ──
        # Checked before the generic Mode 3 "JSON array" catch-all below: FAQ's and
        # Citation Timeline's own prompts also contain the substring "JSON array" and
        # would otherwise be misrouted to Mode 3's canned follow-up-questions response
        # (a JSON array of plain strings) -- for FAQ that degrades to an empty FAQ list
        # (the caller filters out any array item that isn't a dict), and for Citation
        # Timeline's per-source bibliography-extraction call it's the same silent
        # empty-list degradation (also dict-shape-filtered) rather than a crash --
        # still wrong content for a test asserting real mock data came back.
        if "frequently asked questions with grounded answers" in system:
            return _MockAIMessage(json.dumps([
                {
                    "question": "What is the main topic of these sources (mock)?",
                    "answer": "This is a mock grounded FAQ answer (BEESEARCH_MOCK_LLM=1).",
                    "sources": [1],
                },
                {
                    "question": "What methodology do the sources use (mock)?",
                    "answer": "This is a second mock grounded FAQ answer (BEESEARCH_MOCK_LLM=1).",
                    "sources": [1, 2],
                },
            ]))

        if "extracting bibliography entries from an academic paper" in system:
            src_match = re.search(r"\(Source (\d+): ([^)]+)\)", human)
            src_num = src_match.group(1) if src_match else "1"
            return _MockAIMessage(json.dumps([
                {"year": "2020", "authors": "Mock Author A et al.", "title": f"Mock Cited Work {src_num}-1"},
                {"year": "2018", "authors": "Mock Author B", "title": f"Mock Cited Work {src_num}-2"},
            ]))

        if "guessing its key idea or contribution" in system:
            titles = re.findall(r"^\d+\.\s*(.+)$", human, re.MULTILINE)
            gists = [f"Mock one-line gist for '{t[:40]}' (BEESEARCH_MOCK_LLM=1)." for t in titles]
            return _MockAIMessage(json.dumps(gists or ["Mock one-line gist (BEESEARCH_MOCK_LLM=1)."]))

        if "knowledge analyst. Extract key concepts from the sources" in system:
            return _MockAIMessage(json.dumps({
                "central": "Mock Central Topic",
                "branches": [
                    {"concept": "Mock Branch A", "sub_concepts": ["Mock Sub A1", "Mock Sub A2"]},
                    {"concept": "Mock Branch B", "sub_concepts": ["Mock Sub B1"]},
                ],
            }))

        if "You are a knowledge graph extractor" in system:
            return _MockAIMessage(json.dumps({
                "nodes": [
                    {"id": "n1", "label": "Mock Standalone Topic", "type": "concept"},
                    {"id": "n2", "label": "Mock Standalone Method", "type": "method"},
                    {"id": "n3", "label": "Mock Standalone Dataset", "type": "dataset"},
                ],
                "edges": [
                    {"from": "n1", "to": "n2", "label": "uses"},
                    {"from": "n2", "to": "n3", "label": "applied to"},
                ],
            }))

        if "methodology, findings, and implications of the provided source" in system:
            names = re.findall(r"\[Source \d+: ([^\]\n]+)\]", human)
            name = names[0] if names else "the source document"
            return _MockAIMessage(
                f"## Overview\nThis is a mock single-source summary of '{name}' generated by the "
                "dev-only mock LLM (BEESEARCH_MOCK_LLM=1) because no Ollama server is configured.\n\n"
                "## Methodology\nMock methodology paragraph.\n\n"
                "## Key Findings\nMock key findings paragraph.\n\n"
                "## Implications\nMock implications paragraph."
            )

        if "research analyst synthesizing multiple documents" in system:
            names = re.findall(r"\[Source \d+: ([^\]\n]+)\]", human)
            cited = ", ".join(names[:3]) if names else "the provided sources"
            return _MockAIMessage(
                f"## Overview\nThis is a mock cross-document summary generated by the dev-only "
                f"mock LLM (BEESEARCH_MOCK_LLM=1) covering {cited}.\n\n"
                "## Common Themes\nMock shared themes identified across the sources.\n\n"
                "## Complementary Contributions\nMock description of how the sources build on "
                "each other.\n\n"
                "## Contradictions & Gaps\nNo contradictions identified (mock).\n\n"
                "## Key Takeaways\nThis stands in for a real structured cross-document synthesis."
            )

        if "formal literature review" in system:
            nums = re.findall(r"^\[(\d+)\]", human, re.MULTILINE)[:2] or ["1"]
            markers = "".join(f"[{n}]" for n in nums)
            return _MockAIMessage(
                "# Literature Review\n\n"
                f"## 1. Introduction\nThis is a mock literature review introduction {markers}, "
                "generated by the dev-only mock LLM (BEESEARCH_MOCK_LLM=1).\n\n"
                "## 2. Background & Context\nMock background paragraph.\n\n"
                "## 3. Methodological Approaches\nMock methodology paragraph.\n\n"
                f"## 4. Key Findings & Evidence\nMock key finding {markers}.\n\n"
                "## 5. Critical Analysis\nMock critical analysis paragraph.\n\n"
                "## 6. Conclusion\nMock conclusion paragraph."
            )

        if "spoken audio summary script" in system:
            name_match = re.search(r'notebook called "([^"]+)"', human)
            name = name_match.group(1) if name_match else "this notebook"
            return _MockAIMessage(
                f"This is a mock audio summary script for {name}, generated by the dev-only mock "
                "LLM because no Ollama server is configured. Additionally, it stands in for a real "
                "spoken-word summary of the notebook's sources. Finally, this mock script "
                "demonstrates the text-to-speech pipeline end to end."
            )

        if "research analyst comparing two documents" in system:
            a_match = re.search(r"SOURCE A: ([^\n]+)", human)
            b_match = re.search(r"SOURCE B: ([^\n]+)", human)
            name_a = a_match.group(1) if a_match else "Source A"
            name_b = b_match.group(1) if b_match else "Source B"
            return _MockAIMessage(
                "## Source Comparison\n\n"
                f"### Overview\nMock overview of '{name_a}'. Mock overview of '{name_b}'.\n\n"
                "### Common Ground\nMock shared themes between the two sources.\n\n"
                "### Unique Contributions\n"
                "| Aspect | Source A | Source B |\n|---|---|---|\n| Mock aspect | Mock A detail | Mock B detail |\n\n"
                "### Contradictions\nNo contradictions identified (mock).\n\n"
                "### Synthesis\nThis stands in for a real combined-insight synthesis "
                "(BEESEARCH_MOCK_LLM=1)."
            )

        if "Create a comparison table across all sources" in system:
            return _MockAIMessage(
                "| Dimension | Source 1 | Source 2 |\n"
                "|-----------|----------|----------|\n"
                "| Research / Study type | Mock type A | Mock type B |\n"
                "| Sample size / Data scope | Mock scope A | Mock scope B |\n"
                "| Key methodology | Mock method A | Mock method B |\n"
                "| Primary findings | Mock finding A | Mock finding B |\n"
                "| Limitations | Mock limitation A | Mock limitation B |\n"
                "| Year / Period | 2023 | 2024 |\n\n"
                "**Synthesis** — This is a mock synthesis paragraph (BEESEARCH_MOCK_LLM=1) "
                "standing in for a real cross-source agreement/difference analysis."
            )

        # ── Mode 2 (Research Notebook) Explain tab branches (Phase D) ────────
        # Checked before the generic Mode 3 "JSON array" catch-all below: the
        # concept-name-extractor's own system prompt ("Return only valid JSON
        # arrays.") contains the literal substring "JSON array" and would
        # otherwise be misrouted to Mode 3's canned follow-up-questions
        # response (a JSON array of plain strings) -- harmless-looking, but
        # storyteller_node's caller treats the result as a list of concept
        # names, so it would silently poison new_concepts with the wrong text
        # rather than crash. Same defensive-ordering issue already solved for
        # Phase C's FAQ/Citation Timeline branches above.
        if "You are a document coverage assessor" in system:
            return _MockAIMessage(json.dumps({
                "score": 8,
                "reason": "Mock coverage assessment (BEESEARCH_MOCK_LLM=1) — documents adequately "
                "cover this question.",
            }))

        if "You are a Research Partner" in system:
            question_match = re.search(r"USER QUESTION:\s*(.+)", human)
            question = question_match.group(1).strip() if question_match else "the question"
            doc_nums = re.findall(r"^\[(\d+)\]", human, re.MULTILINE)
            online_nums = re.findall(r"^\[Source (\d+)\]", human, re.MULTILINE)
            if online_nums:
                doc_cite = f" [{doc_nums[0]}]" if doc_nums else ""
                body = (
                    f'**From your documents:**\nThis is a mock Explain answer to "{question}"{doc_cite}, '
                    "generated by the dev-only mock LLM (BEESEARCH_MOCK_LLM=1) because no Ollama server "
                    "is configured.\n\n"
                    "**Why online search was needed:**\nThe uploaded documents left a mock coverage gap "
                    "(BEESEARCH_MOCK_LLM=1) that this stands in for filling.\n\n"
                    f"**From online sources:**\nThis fills the gap using [Source {online_nums[0]}], a "
                    "mock online source standing in for a real search result."
                )
            else:
                cite = f" [{doc_nums[0]}]" if doc_nums else ""
                body = (
                    f'This is a mock Explain answer to "{question}"{cite}, generated by the dev-only '
                    "mock LLM (BEESEARCH_MOCK_LLM=1) because no Ollama server is configured. It stands "
                    f"in for a real explanation in the requested style and audience level{cite}."
                )
            sq = json.dumps({"suggested_questions": [
                "Can you explain that with a different analogy?",
                "What's a concrete example of this?",
                "How does this connect to what we discussed earlier?",
            ]})
            return _MockAIMessage(f"{body}\n{sq}")

        if "You extract concept names from explanations" in system:
            return _MockAIMessage(json.dumps(["Mock Concept A", "Mock Concept B"]))

        if "You are a concept-map extractor" in system:
            return _MockAIMessage(json.dumps({
                "central": "Mock Central Concept",
                "related": [
                    {"label": "Mock Related Idea A", "relation": "enables"},
                    {"label": "Mock Related Idea B", "relation": "depends on"},
                    {"label": "Mock Related Idea C", "relation": "is a type of"},
                ],
            }))

        # ── Mode 2 (Research Notebook) Research Report branches (Phase E) ────
        # `agents/graph.py` is a separate, older pipeline -- none of its three
        # prompts share wording with any branch above, but they're grouped
        # here with the other Mode 2 sections for consistency.
        if "focused search queries suitable for arXiv and Semantic Scholar" in system:
            goal_match = re.search(r"Research goal:\s*(.+)", human)
            goal = goal_match.group(1).strip() if goal_match else "the topic"
            return _MockAIMessage(f"{goal} systematic review\n{goal} recent advances\n{goal} applications")

        if "Markdown research report grounded in the provided sources" in system:
            goal_match = re.search(r"Research goal:\s*(.+)", human)
            goal = goal_match.group(1).strip() if goal_match else "the research goal"
            src_nums = re.findall(r"\[Source (\d+):", human)
            paper_nums = re.findall(r"\[Paper (\d+):", human)
            web_nums = re.findall(r"\[Web (\d+):", human)
            cite = (
                f"[Source {src_nums[0]}]" if src_nums
                else f"[Paper {paper_nums[0]}]" if paper_nums
                else f"[Web {web_nums[0]}]" if web_nums
                else ""
            )
            return _MockAIMessage(
                f"# Mock Research Report: {goal}\n\n"
                "## Executive Summary\n"
                f"This is a mock executive summary generated by the dev-only mock LLM "
                f"(BEESEARCH_MOCK_LLM=1) because no Ollama server is configured {cite}.\n\n"
                "## Background and Context\n"
                "Mock background paragraph.\n\n"
                "## Key Findings\n"
                f"1. Mock key finding one {cite}.\n"
                "2. Mock key finding two.\n"
                "3. Mock key finding three.\n\n"
                "## Analysis and Discussion\n"
                "Mock analysis paragraph standing in for a real critical discussion of the "
                "gathered sources.\n\n"
                "## Conclusions\n"
                "Mock conclusion paragraph.\n\n"
                "## Limitations\n"
                "This is a mock limitations paragraph (BEESEARCH_MOCK_LLM=1)."
            )

        if "Score this research report on five dimensions" in system:
            return _MockAIMessage(json.dumps({
                "relevance": 4,
                "depth": 4,
                "clarity": 5,
                "evidence": 4,
                "overall": 4,
                "summary": "Mock evaluation summary (BEESEARCH_MOCK_LLM=1).",
            }))

        if "JSON array" in system:
            return _MockAIMessage(json.dumps([
                "What do other studies find on this topic?",
                "How does this compare across different populations?",
                "What are the key limitations of this evidence?",
            ]))

        # ── Mode 2 (Research Notebook) chat branch ───────────────────────────
        # Checked before the Mode 3 NUMBERED SOURCES branch below: both prompts
        # share the same "QUESTION: ..." / numbered-excerpt shape, so this must
        # come first to give a notebook-flavored answer instead of Mode 3's.
        if "Research Notebook assistant" in system:
            question_match = re.search(r"QUESTION:\s*(.+)", human)
            question = question_match.group(1).strip() if question_match else "the question"
            cited = re.findall(r"\[(\d+)\]", human)[:2] or ["1"]
            markers = " ".join(f"[{n}]" for n in cited)
            answer = (
                f'This is a mock grounded notebook answer to "{question}" {markers}, generated by '
                "the dev-only mock LLM (BEESEARCH_MOCK_LLM=1) because no Ollama server is configured. "
                f"It stands in for a real answer grounded strictly in this notebook's sources {markers}."
            )
            sq = json.dumps({"suggested_questions": [
                "What other sources discuss this topic?",
                "Can you summarize the key findings?",
                "What are the limitations mentioned in the sources?",
            ]})
            return _MockAIMessage(f"{answer}\n{sq}")

        if "NUMBERED SOURCES" in human:
            question_match = re.search(r"QUESTION:\s*(.+)", human)
            question = question_match.group(1).strip() if question_match else "the question"
            cited = re.findall(r"^\[(\d+)\]", human, re.MULTILINE)[:2] or ["1"]
            markers = " ".join(f"[{n}]" for n in cited)
            return _MockAIMessage(
                f'This is a mock grounded answer to "{question}" {markers}, generated by the '
                "dev-only mock LLM (BEESEARCH_MOCK_LLM=1) because no Ollama server is configured. "
                f"It stands in for a real literature-grounded answer {markers} so the full "
                "ask → answer → citations flow can be exercised end-to-end."
            )

        return _MockAIMessage(
            "This is a mock general-knowledge answer generated by the dev-only mock LLM "
            "(BEESEARCH_MOCK_LLM=1) because no published sources were retrieved and no Ollama "
            "server is configured. In a real run this would be an LLM answer with an explicit "
            "not-grounded caveat."
        )


def install_mock_llm() -> None:
    """Monkeypatch ``langchain_ollama.ChatOllama`` with :class:`MockChatOllama`.

    Must be called before any ``agents.*`` module is imported.
    """
    import langchain_ollama

    langchain_ollama.ChatOllama = MockChatOllama
