"""backend/app/mock_search.py
───────────────────────────
Dev-only stand-in for ``tools.search_tools.AcademicSearcher`` / ``WebSearcher``,
enabled by the same ``BEESEARCH_MOCK_LLM=1`` flag as ``mock_llm.py``. Combined,
the two let the full ask → search → answer → citations flow be exercised
deterministically and without network access (manual browser testing,
Playwright E2E) when no search backends or Ollama server are reachable.

Returns the same ``Paper``/``WebResult`` dataclasses ``tools.search_tools``
defines (just pre-populated), so every downstream consumer
(``build_numbered_sources``, ``build_citations``, ``Paper.to_apa()``) runs
unmodified against real-shaped data.

Unlike ``ChatOllama``, ``AcademicSearcher``/``WebSearcher`` are imported lazily
inside ``agents.research_assistant.search_literature()`` (``from
tools.search_tools import AcademicSearcher`` *inside* the function body), so
patching ``tools.search_tools``'s module attributes works regardless of import
order or when ``install_mock_search()`` is called relative to ``agents.*``
imports -- no early-binding concern here, unlike ``install_mock_llm()``.
"""

from __future__ import annotations

import time
from typing import List

from tools.search_tools import Paper, WebResult

# Small artificial delays so callers polling job status (e.g. the React
# frontend's stage labels, or an E2E test) can observe the "searching" stage
# rather than have it complete instantly between polls -- a real search
# against Google Scholar/arXiv/Semantic Scholar/DuckDuckGo is never instant.
_MOCK_ACADEMIC_DELAY_SECONDS = 0.5
_MOCK_WEB_DELAY_SECONDS = 0.3


class MockAcademicSearcher:
    """Drop-in replacement for AcademicSearcher with two deterministic fake Papers."""

    def search(self, query: str, max_per_source: int = 6, include_crossref: bool = False) -> List[Paper]:
        time.sleep(_MOCK_ACADEMIC_DELAY_SECONDS)
        topic = query.strip().rstrip("?") or "the topic"
        papers = [
            Paper(
                title=f"A Survey of {topic}",
                authors=["A. Researcher", "B. Scholar"],
                year=2023,
                abstract=(
                    f"This mock paper stands in for a real search result on '{query}', generated "
                    "by the dev-only mock search (BEESEARCH_MOCK_LLM=1) because no network search "
                    "backend is configured."
                ),
                url="https://example.org/mock-paper-1",
                journal="Mock Journal of Research",
                source="arxiv",
                citation_count=12,
            ),
            Paper(
                title=f"Recent Advances Related to {topic}",
                authors=["C. Investigator"],
                year=2021,
                abstract=(
                    "A second mock paper so citation grounding (multiple [n] markers) and the "
                    "academic-source count can both be exercised end-to-end."
                ),
                url="https://example.org/mock-paper-2",
                journal="Mock Proceedings",
                source="semantic_scholar",
                citation_count=4,
            ),
        ]
        return papers[:max_per_source]


class MockWebSearcher:
    """Drop-in replacement for WebSearcher with one deterministic fake WebResult."""

    def search(self, query: str, max_results: int = 5) -> List[WebResult]:
        time.sleep(_MOCK_WEB_DELAY_SECONDS)
        results = [
            WebResult(
                title=f"Mock web result for {query}",
                url="https://example.org/mock-web-1",
                snippet=(
                    "A mock DuckDuckGo result standing in for a real web search, generated by the "
                    "dev-only mock search (BEESEARCH_MOCK_LLM=1)."
                ),
                source="duckduckgo",
            ),
        ]
        return results[:max_results]


def install_mock_search() -> None:
    """Monkeypatch ``tools.search_tools.AcademicSearcher``/``WebSearcher`` with deterministic fakes.

    Safe to call at any point before a request is handled -- unlike
    ``install_mock_llm()``, there is no module-namespace early-binding to race
    against here.
    """
    import tools.search_tools as search_tools

    search_tools.AcademicSearcher = MockAcademicSearcher
    search_tools.WebSearcher = MockWebSearcher
