"""tools/preregistration.py — OSF-style SR pre-registration template"""
from __future__ import annotations
from datetime import datetime
from typing import Any, Dict, List

def generate_preregistration(research_question: str, inclusion_criteria: List[str], exclusion_criteria: List[str], search_queries: List[str], author_name: str = "BeeSearch User") -> str:
    today = datetime.today().strftime("%B %d, %Y")
    inc_block = "\n".join(f"- {c}" for c in inclusion_criteria) or "- *(not specified)*"
    exc_block = "\n".join(f"- {c}" for c in exclusion_criteria) or "- *(not specified)*"
    query_block = "\n".join(f"{i+1}. `{q}`" for i,q in enumerate(search_queries)) if search_queries else "*(not yet generated)*"
    return f"""# Systematic Review Pre-Registration\n\n**Title:** Pre-Registration: {research_question[:100]}\n\n**Date:** {today}\n\n**Authors:** {author_name}\n\n---\n\n## 1. Research Question\n\n{research_question}\n\n## 2. Inclusion Criteria\n\n{inc_block}\n\n## 3. Exclusion Criteria\n\n{exc_block}\n\n## 4. Search Strategy\n\n{query_block}\n\n## 5. Risk of Bias\n\n- **RCTs:** Cochrane RoB 2 (5 domains)\n- **Observational:** ROBINS-I (7 domains)\n\n## 6. Synthesis\n\n- Narrative synthesis\n- GRADE evidence grading\n- Contradiction analysis\n- Sensitivity analysis\n\n---\n\n*Generated by BeeSearch on {today}.*  \n*Edit before registering at [OSF Registries](https://osf.io/registries).*\n"""

def generate_prisma_checklist(state: Dict[str, Any]) -> str:
    items = [
        ("Title", "Report identified as systematic review", bool(state.get("research_question"))),
        ("Eligibility criteria", "Inclusion/exclusion specified", bool(state.get("inclusion_criteria") or state.get("exclusion_criteria"))),
        ("Information sources", "Databases searched", True),
        ("Search strategy", "Full search queries", bool(state.get("search_queries"))),
        ("Study records", "PRISMA flow diagram", bool(state.get("prisma_flow"))),
        ("Data collection", "Evidence table", bool(state.get("evidence_table"))),
        ("Risk of bias", "RoB assessment", bool(state.get("rob_table"))),
        ("Synthesis", "Narrative synthesis", bool(state.get("narrative_synthesis"))),
        ("Certainty", "GRADE applied", bool(state.get("grade_results"))),
        ("Conclusions", "Conclusion provided", bool(state.get("conclusion"))),
    ]
    lines = ["# PRISMA 2020 Checklist", "", "| Item | Description | Status |", "| --- | --- | --- |"]
    for item, desc, done in items:
        lines.append(f"| {item} | {desc} | {'✅' if done else '⬜'} |")
    completed = sum(1 for *_, done in items if done)
    lines += ["", f"**Completed: {completed}/{len(items)} items**"]
    return "\n".join(lines)
