"""
tools/proposal_tools.py
────────────────────────
Utility helpers for ProposalGPT:

  - build_proposal_docx()       → Full DOCX proposal document
  - build_budget_csv()          → Budget spreadsheet as CSV bytes
  - assemble_full_proposal_md() → Assemble all sections into one Markdown doc
  - SECTION_ORDER               → Canonical proposal section ordering
"""

from __future__ import annotations

import csv
import io
import json
from typing import Any, Dict, List


# ── Canonical section ordering ─────────────────────────────────────────────────

SECTION_ORDER = [
    ("executive_summary",     "Executive Summary"),
    ("excellence",            "Excellence"),
    ("scientific_background", "Scientific Background"),
    ("literature_review",     "Literature Review"),
    ("state_of_art",          "State of the Art"),
    ("objectives",            "Objectives"),
    ("methodology",           "Methodology"),
    ("risk_management",       "Risk Management"),
    ("impact",                "Impact"),
    ("dissemination",         "Dissemination & Communication"),
    ("exploitation",          "Exploitation"),
    ("ethics",                "Ethics"),
    ("sustainability",        "Sustainability"),
    ("budget_justification",  "Budget Justification"),
    ("consortium_description","Consortium Description"),
    ("management_structure",  "Management Structure"),
    ("data_management",       "Data Management Plan"),
]


def assemble_full_proposal_md(state: dict, include_improved: bool = True) -> str:
    """Assemble all proposal sections into a single Markdown document."""
    improved = state.get("improved_sections", {}) if include_improved else {}
    lines = []

    title = state.get("call_title", "Research Proposal")
    agency = state.get("funding_agency", "")
    session_id = state.get("session_id", "")

    lines += [
        f"# {title}",
        f"*Funding Agency: {agency}*" if agency else "",
        f"*Generated by ProposalGPT — Session {session_id}*",
        "",
        "---",
        "",
    ]

    for field, heading in SECTION_ORDER:
        text = improved.get(field) or state.get(field, "")
        if text and text.strip():
            lines += [f"## {heading}", "", text.strip(), "", "---", ""]

    # Work Packages table
    wps = state.get("work_packages", [])
    if wps:
        lines += ["## Work Packages", ""]
        lines += ["| ID | Title | Months | Lead |", "|---|---|---|---|"]
        for wp in wps:
            lines.append(
                f"| {wp.get('id','')} | {wp.get('title','')} | "
                f"{wp.get('months','')} | {wp.get('lead','')} |"
            )
        lines.append("")

    # Deliverables
    dels = state.get("deliverables", [])
    if dels:
        lines += ["## Deliverables", ""]
        lines += ["| ID | Title | Type | Month | WP |", "|---|---|---|---|---|"]
        for d in dels:
            lines.append(
                f"| {d.get('id','')} | {d.get('title','')} | "
                f"{d.get('type','')} | {d.get('month','')} | {d.get('wp','')} |"
            )
        lines.append("")

    # Milestones
    mss = state.get("milestones", [])
    if mss:
        lines += ["## Milestones", ""]
        lines += ["| ID | Title | Month | Verification |", "|---|---|---|---|"]
        for m in mss:
            lines.append(
                f"| {m.get('id','')} | {m.get('title','')} | "
                f"{m.get('month','')} | {m.get('verification','')} |"
            )
        lines.append("")

    # Budget summary
    budget_table = state.get("budget_summary_table", "")
    if budget_table:
        lines += ["## Budget Summary", "", budget_table, ""]

    return "\n".join(lines)


def build_proposal_docx(state: dict, include_improved: bool = True) -> bytes:
    """Build a full DOCX proposal document from state."""
    from io import BytesIO
    from docx import Document
    from docx.shared import Pt, RGBColor, Inches
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    improved = state.get("improved_sections", {}) if include_improved else {}
    doc = Document()

    # ── Title page ────────────────────────────────────────────────────────
    title = state.get("call_title", "Research Proposal")
    agency = state.get("funding_agency", "")

    title_para = doc.add_heading(title, 0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    if agency:
        sub = doc.add_paragraph(f"Funding Agency: {agency}")
        sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
        sub.runs[0].italic = True

    doc.add_page_break()

    # ── Sections ─────────────────────────────────────────────────────────
    def _add_section(heading: str, text: str) -> None:
        if not text or not text.strip():
            return
        doc.add_heading(heading, level=1)
        for para in text.strip().split("\n\n"):
            para = para.strip()
            if not para:
                continue
            if para.startswith("## "):
                doc.add_heading(para[3:], level=2)
            elif para.startswith("# "):
                doc.add_heading(para[2:], level=1)
            elif para.startswith("### "):
                doc.add_heading(para[4:], level=3)
            elif para.startswith("| "):
                # Table (simple rendering as code block)
                p = doc.add_paragraph(para)
                p.style = "No Spacing"
            else:
                para_clean = para.replace("**", "").replace("*", "")
                doc.add_paragraph(para_clean)

    for field, heading in SECTION_ORDER:
        text = improved.get(field) or state.get(field, "")
        _add_section(heading, text)

    # ── Work Packages ─────────────────────────────────────────────────────
    wps = state.get("work_packages", [])
    if wps:
        doc.add_heading("Work Packages", level=1)
        for wp in wps:
            doc.add_heading(f"{wp.get('id','')} — {wp.get('title','')}", level=2)
            doc.add_paragraph(wp.get("description", ""))
            doc.add_paragraph(f"Duration: {wp.get('months','')} | Lead: {wp.get('lead','')}")
            tasks = wp.get("tasks", [])
            if tasks:
                for t in tasks:
                    doc.add_paragraph(t, style="List Bullet")

    # ── Budget ────────────────────────────────────────────────────────────
    budget_table = state.get("budget_summary_table", "")
    if budget_table:
        doc.add_heading("Budget Summary", level=1)
        doc.add_paragraph(budget_table)

    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()


def build_budget_csv(state: dict) -> bytes:
    """Build a CSV budget breakdown from state."""
    buf = io.StringIO()
    writer = csv.writer(buf)

    currency = state.get("budget_constraints", {}).get("currency", "EUR")

    # Personnel
    writer.writerow(["PERSONNEL BUDGET"])
    writer.writerow(["Role", "Months", f"Rate/Month ({currency})", f"Total ({currency})"])
    for p in state.get("budget_personnel", []):
        writer.writerow([p.get("role", ""), p.get("months", ""), p.get("rate_per_month", 0), p.get("total", 0)])
    writer.writerow([])

    # Equipment
    writer.writerow(["EQUIPMENT BUDGET"])
    writer.writerow(["Item", f"Cost ({currency})", "Justification"])
    for e in state.get("budget_equipment", []):
        writer.writerow([e.get("item", ""), e.get("cost", 0), e.get("justification", "")])
    writer.writerow([])

    # Travel
    writer.writerow(["TRAVEL BUDGET"])
    writer.writerow(["Destination", "Purpose", f"Cost ({currency})"])
    for t in state.get("budget_travel", []):
        writer.writerow([t.get("destination", ""), t.get("purpose", ""), t.get("cost", 0)])
    writer.writerow([])

    # Summary
    pers_total = sum(float(p.get("total", 0)) for p in state.get("budget_personnel", []))
    equip_total = sum(float(e.get("cost", 0)) for e in state.get("budget_equipment", []))
    travel_total = sum(float(t.get("cost", 0)) for t in state.get("budget_travel", []))
    indirect = float(state.get("budget_indirect", 0))
    grand_total = float(state.get("budget_total", 0))

    writer.writerow(["SUMMARY"])
    writer.writerow(["Category", f"Amount ({currency})"])
    writer.writerow(["Personnel", f"{pers_total:,.2f}"])
    writer.writerow(["Equipment", f"{equip_total:,.2f}"])
    writer.writerow(["Travel", f"{travel_total:,.2f}"])
    writer.writerow([f"Indirect Costs ({int(state.get('budget_indirect_rate', 0.25)*100)}%)", f"{indirect:,.2f}"])
    writer.writerow(["TOTAL", f"{grand_total:,.2f}"])

    return buf.getvalue().encode("utf-8")


def section_word_count(state: dict) -> Dict[str, int]:
    """Return word count per generated section."""
    counts = {}
    for field, heading in SECTION_ORDER:
        text = state.get("improved_sections", {}).get(field) or state.get(field, "")
        counts[heading] = len(text.split()) if text else 0
    return counts
