import { expect, test } from "@playwright/test";

/**
 * Runs against the REAL FastAPI backend (with BEESEARCH_MOCK_LLM=1, see
 * playwright.config.ts's webServer) and the production Vite build (`vite
 * preview`), so this exercises the full React -> HTTP -> FastAPI -> LangGraph
 * PRISMA pipeline end-to-end -- no mocked fetch, no fake timers, just the
 * dev-only mock LLM (backend/app/mock_llm.py) and mock search
 * (backend/app/mock_search.py) standing in for Ollama and the real academic
 * search backends.
 *
 * The mock search returns 2 deterministic papers per query, and query
 * generation falls back to exactly 2 queries (the research question itself,
 * plus "<question> systematic review") -- so with every paper title distinct
 * across the two queries (no dedup collisions) and every mock screening
 * decision forced to INCLUDE, the PRISMA flow is fully deterministic:
 * 4 identified, 4 included, 0 excluded. See backend/app/mock_llm.py's
 * "Mode 1 (Systematic Review) branches" comment for the full call-site map.
 */

test("renders the initial controls", async ({ page }) => {
  await page.goto("/?mode=mode1");

  await expect(page.getByRole("heading", { name: "Mode 1 — Systematic Literature Review" })).toBeVisible();
  await expect(page.getByLabel("Research question")).toHaveValue("");
  await expect(page.getByLabel("Inclusion criteria (one per line)")).toHaveValue("");
  await expect(page.getByLabel("Exclusion criteria (one per line)")).toHaveValue("");
  await expect(page.getByRole("button", { name: "Run Systematic Review" })).toBeEnabled();
});

test("shows a validation warning for a blank question without contacting the backend", async ({ page }) => {
  await page.goto("/?mode=mode1");

  await page.getByRole("button", { name: "Run Systematic Review" }).click();
  await expect(page.getByText("Please enter a research question.")).toBeVisible();

  await page.getByLabel("Research question").fill("a");
  await expect(page.getByText("Please enter a research question.")).toHaveCount(0);
});

test("runs a systematic review end-to-end and renders a deterministic PRISMA flow with synthesis", async ({
  page,
}) => {
  await page.goto("/?mode=mode1");

  await page.getByLabel("Research question").fill("Sleep and memory?");
  await page.getByLabel("Inclusion criteria (one per line)").fill("Peer-reviewed empirical studies\nHuman participants");
  await page.getByLabel("Exclusion criteria (one per line)").fill("Animal studies");
  await page.getByRole("button", { name: "Run Systematic Review" }).click();

  // Screening makes one LLM call per paper (4 papers x ~0.4s mock delay each),
  // comfortably longer than the 700ms poll interval, so this stage is reliably
  // observable over real network polling (unlike the ~0.4s single-call stages).
  await expect(page.getByText("Screening papers by title/abstract…")).toBeVisible({ timeout: 30_000 });

  await expect(page.getByText("Done.")).toBeVisible({ timeout: 60_000 });
  await expect(page.getByText(/Failed:|Workflow error:/)).toHaveCount(0);

  await expect(
    page.getByText("Queries: 2 · Identified: 4 · Included: 4 · Excluded: 0"),
  ).toBeVisible();

  await expect(page.getByText(/This is a mock narrative synthesis generated by the dev-only mock LLM/)).toBeVisible();
  await expect(page.getByText("Mock theme A")).toBeVisible();
  await expect(page.getByText("Mock research gap requiring further study.")).toBeVisible();
  await expect(page.getByText("This is a mock conclusion paragraph")).toBeVisible();

  // GRADE certainty never renders for SR (sr_eval_node's eval_result has no
  // "overall" key, and grade_results degrades to {} here) -- pre-existing
  // Streamlit behavior the React port faithfully reproduces.
  await expect(page.getByText(/Certainty of evidence/)).toHaveCount(0);
  await expect(page.getByText(/Quality Score/)).toHaveCount(0);

  const tablist = page.getByRole("tablist", { name: "Systematic review results" });
  await tablist.getByRole("tab", { name: "Evidence" }).click();
  await expect(page.getByText("Evidence Table (4 included papers)")).toBeVisible();

  await tablist.getByRole("tab", { name: "Write-up & Export" }).click();
  await expect(page.getByText("Search Queries Used")).toBeVisible();
  await expect(page.getByRole("button", { name: "Download as Markdown" })).toBeVisible();
});
